### ISSUE TITLE
Compiled JAR?

### ISSUE THREAD

**Issue by ghost** [DaMatrix/PorkBot#1]
........................

**Comment by DaMatrix** [comment]
Why would you even need a compiled jar? You can just use the invite on http://www.daporkchop.tk/porkbot to add it to your server. If you really need to run it yourself, use the compile.sh script to compile it and then start.sh to launch.

**Comment by ghost** [comment]
......................

**Comment by DaMatrix** [comment]
Why would you need a jar though? I don't get it.

**Comment by ghost** [comment]
...................

**Comment by DaMatrix** [comment]
This isn't supposed to be run yourself. You don't go around asking for the download of e.g. Tatsumaki saying "i wanna download 2 change profile pic kthanks". If you want the bot, invite it.
