### ISSUE TITLE
Several mc commands aren't working

### ISSUE THREAD

**Issue by nate2014jatc** [DaMatrix/PorkBot#2]
mcavatar, mcskin, mcskin, mcicon, mcping, mclatency, and mcquery are failing for me, providing no debug data

**Comment by DaMatrix** [comment]
![mclatency](https://user-images.githubusercontent.com/11216106/27518397-737f6e2c-59df-11e7-93c5-dbb5b8a4294b.PNG)
![mcping](https://user-images.githubusercontent.com/11216106/27518401-7382bc8a-59df-11e7-88b1-ab18261b843c.PNG)
![mcquery](https://user-images.githubusercontent.com/11216106/27518399-7380dfd2-59df-11e7-906d-f40cb4a18022.PNG)
![mcskin](https://user-images.githubusercontent.com/11216106/27518396-737e9ede-59df-11e7-96fa-a720c7dbf9d5.PNG)
![mcavatar](https://user-images.githubusercontent.com/11216106/27518398-73806728-59df-11e7-9116-f68af28a9fb4.PNG)
![mcicon](https://user-images.githubusercontent.com/11216106/27518400-7381f80e-59df-11e7-91d2-04b44c564ab4.PNG)
all of those work fine for me. in what way is it failing? just nothing being sent?

**Comment by nate2014jatc** [comment]
Nothing at all is being returned with the options I used. (My personal server, UUID, Username, etc.)

**Comment by DaMatrix** [comment]
hm. can you send me the server ip and name so i can test it out? thanks!

**Comment by nate2014jatc** [comment]
Server IP is “raxventus.ddns.net”
Username is “raxventus”

**Comment by DaMatrix** [comment]
both the IP and name work fine for me. make sure that the bot has permission to send embeds, as without that it won't work. permission is called "Embed links"

**Comment by deltanedas** [comment]
please reopen, this is not fixed
